# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NDXt2cormOTOzN-hcp9PZwPeJLHLUn6m

Q1: A company decided to give bonus of 5% to employee if his/her year of service is more than 5 years. Ask user for their salary and year of service and print the net bonus amount.
"""

salary = float(input("Enter your salary: "))
expr = float(input("Enter years of service: "))
if expr > 5: 
  print("The bonus is ", salary*.05)
else: 
  print("Since, year of experience is less than 5, and hence no bonus.")

"""Q2:Take values of length and breadth of a rectangle from user and check if it is square or not."""

l = float(input("Enter length: "))
b = float(input("Enter breadht: "))

if l == b :
  print("It is a square")
else: 
  print("It is not a square")

"""Q3: A school has following rules for grading system:
1. Below 25 - F
2. 25 to 45 - E
3. 45 to 50 - D
4. 50 to 60 - C
5. 60 to 80 - B
6. Above 80 - A

Ask user to enter marks and print the corresponding grade.
"""

marks = float(input("Enter marks: "))
if(marks < 0 or marks > 100):
  print("Invalid Input. Marks should be within 0-100")
elif(marks < 25):
  print("Your grade is F")
elif(marks < 45):
  print("Your grade is E")
elif marks < 50: 
  print("Your grade is D")
elif marks < 60: 
  print("Your grade is C")
elif marks < 80: 
  print("Your grade is B")
else: 
  print("Your grade is A")

"""Q4: Take input of age of 3 people by user and determine oldest and youngest among them.

"""

name1 = float(input("Enter the age of Keju: "))
name2 = float(input("Enter the age of Pappu: "))
name3 = float(input("Enter the age of Akku: "))

if name1 > name2 and name1 > name3: 
  print("Keju is oldest")
  if name2 > name3:
    print("Akku is youngest")
  else: 
    print("Pappu is youngest")
elif name2 > name3:
  print("Pappy is oldest")
  if name1 > name3:
    print("Akku is youngest")
  else: 
    print("Keju is youngest")
else: 
  print("Akku is oldest")
  if name1 > name2: 
    print("Pappu is youngest")
  else: 
    print("Keju is youngest")

#Second Method (more easy)
name1 = float(input("Enter the age of Keju: "))
name2 = float(input("Enter the age of Pappu: "))
name3 = float(input("Enter the age of Akku: "))

if name1 > name2 and name1 > name3: 
  print("Keju is oldest")
elif name2 > name3:
  print("Pappu is oldest")
else: 
  print("Akku is oldest")

if name1 < name2 and name1 < name3:
  print("Keju is Youngest")
elif name2 < name3: 
  print("Pappu is youngest")
else:
  print("Akku is youngest")

"""Q5: A student will not be allowed to sit in exam if his/her attendence is less than 75%.
Take following input from user
1. Number of classes held
2. Number of classes attended.

And print
1. percentage of class attended
2.  Is student is allowed to sit in exam or not.
"""

ch = float(input("Enter the number of classes held: "))
ca = float(input("Enter the number of classes attended: "))

pa = (ca/ch) * 100

if pa > 100: 
  print("Class attended can not be more than held.")
elif pa < 75: 
  print("You are not allowed to sit in the exam.")
else: 
  print("You are allowed to sit in the exam.")

if pa <= 100:
  print("Your attendance is", pa)

#Above code make sure, no message is written twice.

"""Q6: Write a program to check whether the last digit of a number (entered by user) is divisible by 3 or not."""

num = float(input("Enter any positive integer: "))

ld = num % 10
if ld % 3 == 0:
  print("Last digit of a number is divisible by 3.")
else:
  print("Last digit is not divisible by 3.")

"""Q7: Write a programme that returns present value of an annuity. Take all necessary inputs from the users, and put condition on the validity of each inputs. In case of incorrect input, provide readable message to the user."""

amount = float(input("Enter annuity amount: "))
intt = float(input("Enter rate of interest (in percentage): "))
n = float(input("Enter number of payments made each year: "))

amountc = amount < 0 #amount should be positive
intt = intt / 100
inttc = intt < 0 #interest should be positive
nc1 = n < 0 #fist n check is it is must be positive
nc2 = (n - int(n)) != 0 #n must be integer

#now printing error for each case: 
if amountc: 
  print("Amount should be positive.")
if inttc:
  print("Interest rate should be positive.")
if nc1: 
  print("number of payments must be positive.")
if nc2: 
  print("number of payments must be integer.")

allcond = amountc + inttc + nc1 + nc2 #if any condition above is True then 
# sum of allcond >= 1

if intt == 0 and allcond == 0:
  pva = amount * n
  print("Present value of annuity is", pva)

if intt > 0 and allcond == 0:
  pva = amount * ((1 - (1+intt)**(-n))/intt)
  print("Present value of annuity is", pva)